
sequencing_runs: config/lanes.txt
barcode_map: config/samples.txt

barcodes: /home/scruz/Utils/GBS_wells_adapters.csv
resources_config: config/resources.yaml
bigtmp: tmpdir/

references_file: config/references.txt
    
NGSEP:
    path: /home/scruz/software/NGSEPcore-4.3.1/NGSEPcore_4.3.1.jar
    SingleSampleVariantsDetector:
        h: 0.0001
        maxBaseQS: 30
        minQuality: 40
        maxAlnsPerStartPos: 100
        ignore5: 7
        ignore3: 8
    VCFFilter:
        QC_thresold: 40
demultiplexing:
  re_enzime: "apeKI"

trimmomatic:
    pe:
        trimmer:
          - "LEADING:5"
          - "TRAILING:5"
          - "SLIDINGWINDOW:4:5"
          - "MINLEN:36"
          - "ILLUMINACLIP:data/adapter.fa:2:20:7:2"
  
picard:
    MarkDuplicates: "REMOVE_DUPLICATES=true"

bcftools: '/home/scruz/software/bcftools/bin/bcftools'
bgzip: '/home/scruz/software/htslib/bin/bgzip'
tabix: '/home/scruz/software/htslib/bin/tabix'